import "./global.css";
import { Metadata } from "next";
/*export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}*/

export const metadata: Metadata = {
    title:{
      default:"Aprendiendo next.js", // Marca el titulo por defecto 
      absolute:"",
      template:"Loto Indumentaria - %s", // La %s muestra el nombre de la pagina despues o antes de lo ya escrito
    }
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body>
        <header>Cabecera de la app</header>

        <main>
          {children}
          </main>
          
        <footer>Pie de la app</footer>
        </body>
    </html>
  )
}
