import "./global.css";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body>
        <header>Cabecera de la app</header>

        <main>
          {children}
          </main>
          
        <footer>Pie de la app</footer>
        </body>
    </html>
  )
}
